name: Deploy to AWS S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies and Build
        run: |
          npm ci
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::497588665354:role/portfolio_deploy_role"
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://my-portfolio-site-aslinger --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E1UVFR2BNCK8PA --paths "/*"